### ISSUE TITLE
Gateway - Unable to use approve-token and getting token not supported error 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#10]
**Describe the bug**
While testing the development branch + gateway (source), it was observed that the `gateway approve-token` does not seem to work as expected. In the past when using the connector it would approve but now on the new setup and repository it wont let us and can be reproduce using most of the gateway connectors 

Pancakeswap-BSC
![2023-02-13_10-25](https://user-images.githubusercontent.com/73840223/218362103-c5628e08-dbee-4e5a-b2b0-4284ac568620.png)

Sushiswap-BSC
![2023-02-13_10-25_1](https://user-images.githubusercontent.com/73840223/218361954-afde8b71-eb00-4ff1-ae73-09eb39389464.png)

Pangolin-Avalanche
![2023-02-13_10-37](https://user-images.githubusercontent.com/73840223/218361881-b51596f8-3932-4b75-9f16-71d8bc33338e.png)

```
2023-02-13 11:01:54,307 - 27574 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2023-02-13 11:02:09,193 - 27574 - hummingbot.client.hummingbot_application - INFO - Connector pangolin Tokens 0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7 will now be approved for spending for 'pangolin_avalanche_avalanche'.
2023-02-13 11:02:10,682 - 27574 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/evm/approve failed. See logs for more details.
2023-02-13 11:02:10,682 - 27574 - hummingbot.client.hummingbot_application - ERROR - Error approving tokens: Error on POST https://localhost:15888/evm/approve Error: {'message': 'Token not supported: 0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7', 'httpErrorCode': 500, 'errorCode': 1006, 'stack': 'Error: Token not supported: 0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7\n    at /Users/ralphcomia/hbot/github/gateway/dist/src/chains/ethereum/ethereum.controllers.js:134:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/ralphcomia/hbot/github/gateway/dist/src/chains/ethereum/ethereum.controllers.js:5:58)'}
```

Please see recording below using Pangolin-Avalanche and WAVAX-USDC as example
- Balance and status: ok
- Setup simple amm-arb then start: ok 
- Notice that when we tried to approve the token WAVAX, WBNB and USDC it does not let us with token not supported. 
https://user-images.githubusercontent.com/73840223/218362632-5e498592-7737-4201-a711-2f2a2ca089b3.mov

**Note**: _Users can still manually approve tokens via exchange website

**Steps To Reproduce**
1. Setup client + gateway (source)
2. Select any gateway connector
3. Look for supported tokens, sample WETH, DAI, etc..
4. Run `gateway approve-token` and observe the error message

**Release version**
N/a

**Attachments**
[logs_amm-pangolin-test.log](https://github.com/hummingbot/gateway/files/10718284/logs_amm-pangolin-test.log)
[logs_gateway_app.log.2023-02-13.log](https://github.com/hummingbot/gateway/files/10718289/logs_gateway_app.log.2023-02-13.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
The expected use of command should be ga`teway approve-token <connector> <token-name>` not token address, closing ticket now since its working as expected

![image](https://user-images.githubusercontent.com/73840223/218368259-de62d51d-e989-4e56-89b9-9ad7f0a2fcee.png)
