### ISSUE TITLE
Gateway - Run "gateway connect <amm-connector>" while offline resulting to unhandled error

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#106]
**Describe the bug**
Part of possible improvement on UX is the error responses if user is not aware that gateway is `offline`. 
![image](https://github.com/hummingbot/gateway/assets/73840223/5818c180-6f36-4147-a5a8-45bc56a0db40)

For the `gateway connect` command, this error happens if user trying to setup amm-connector, `uniswap` for example
![image](https://github.com/hummingbot/gateway/assets/73840223/3bb23e0f-5532-46f4-8c6d-2b63d326443c)

```
2023-05-17 11:07:05,771 - 718 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/client/command/gateway_command.py", line 172, in _gateway_connect
    connector_configs: Dict[str, Any] = await self._get_gateway_instance().get_connectors()
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/gateway/gateway_http_client.py", line 255, in get_connectors
    return await self.api_request("get", "connectors", fail_silently=fail_silently)
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/gateway/gateway_http_client.py", line 174, in api_request
    client = self._http_client(self._client_config_map)
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/gateway/gateway_http_client.py", line 82, in _http_client
    ssl_ctx = ssl.create_default_context(cafile=f"{cert_path}/ca_cert.pem")
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
FileNotFoundError: [Errno 2] No such file or directory
```

Suggestion: It would be better if we have a response that `gateway connection is offline` or equivalent for better UX

**Steps To Reproduce**
1. Setup client + gateway on either source/docker build
2. Run `gateway connect <amm-connector>` and observe behavior

**Release version**
Master and Development branch

**Attachments**
// It is important that you attach the required files for us to be able to investigate the issue. 
// Please attach the chain.yml file from your gateway "conf" folder, e.g ethereum.yml
[logs_hummingbot.log](https://github.com/hummingbot/gateway/files/11493950/logs_hummingbot.log)

**Comment by rapcmia** [comment]
Added update to latest development branch that adds `gateway is offline` when gateway is not connected
