### ISSUE TITLE
Improve error handling when users run Gateway commands when Gateway is offline

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#107]
**Describe the bug**
Part of possible improvement on UX is the error responses if user is not aware that gateway is `offline`. 
![image](https://github.com/hummingbot/gateway/assets/73840223/5818c180-6f36-4147-a5a8-45bc56a0db40)

There are instances users forget to setup gateway and directly check the list of available amm-connectors using `gateway list` command resulting to error `Unhandled error in background task: Cannot connect to host localhost:15888 ssl:default` which we believe is expected yet should better handled with simple and user friendly?
![image](https://github.com/hummingbot/gateway/assets/73840223/47e8ecaf-cdf9-4bcd-ac37-426b5c7b2baa)

```
2023-05-17 11:18:30,140 - 886 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/connectors failed. See logs for more details.
2023-05-17 11:18:30,140 - 886 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Cannot connect to host localhost:15888 ssl:default [Connect call failed ('127.0.0.1', 15888)]
Traceback (most recent call last):
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 15888)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/client/command/gateway_command.py", line 415, in _gateway_list
    connector_list: List[Dict[str, Any]] = await self._get_gateway_instance().get_connectors()
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/gateway/gateway_http_client.py", line 255, in get_connectors
    return await self.api_request("get", "connectors", fail_silently=fail_silently)
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/gateway/gateway_http_client.py", line 185, in api_request
    response = await client.get(url)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:15888 ssl:default [Connect call failed ('127.0.0.1', 15888)]
```

**Steps To Reproduce**
1. Setup client + gateway on either source/docker build
2. Run `gateway list` and observe behavior

**Release version**
Master and development branch 

**Attachments**
// It is important that you attach the required files for us to be able to investigate the issue. 
// Please attach the chain.yml file from your gateway "conf" folder, e.g ethereum.yml
[logs_hummingbot.log](https://github.com/hummingbot/gateway/files/11493973/logs_hummingbot.log)

**Comment by fengtality** [comment]
**Description**
* In cases where Gateway is offline, emit an error message "Gateway is offline" in response to commands such as `gateway list` and others
* Handle the error in the log pane to print error message "Gateway is offline" instead of `Unhandled error in background task...`

**Bounty**
* Sponsor: Hummingbot Foundation
* Status: OPEN
* Bounty Amount: 50,000 HBOT
* Developer Payment: 50,000 HBOT (100%)
* Status: Open

**Comment by zedquach** [comment]
I will take this

**Comment by rapcmia** [comment]
Assigned to @zedquach

**Comment by zedquach** [comment]
Starting now.

**Comment by zedquach** [comment]
@fengtality @rapcmia 
Just to clarify, we want to do this for all of gateway commands only right? (Not for all methods)

**Comment by zedquach** [comment]
pr raised
[https://github.com/hummingbot/hummingbot/pull/6350](https://github.com/hummingbot/hummingbot/pull/6350)

**Comment by nikspz** [comment]
@zedquach please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.

May you please mention your discord handle here if you use different nickname here (github vs discord.)

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @zedquach. The fix has been deployed on development branch and next hummingbot version 1.17.0
