### ISSUE TITLE
Gateway - Unhandled error in background task: 'AMM'

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#108]
**Describe the bug**
When checking latest client and gateway development setup, an `hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'AMM'` occurred after successfully connected AMM-connector wallets 

![image](https://github.com/hummingbot/gateway/assets/73840223/27db898a-3491-492b-b66f-29abafb6e500)

```
2023-05-19 18:54:39,322 - 5669 - hummingbot.core.gateway.gateway_status_monitor - INFO - Gateway Service is ONLINE.
2023-05-19 18:55:22,297 - 5669 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'AMM'
Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/client/command/gateway_command.py", line 321, in _gateway_connect
    AllConnectorSettings.create_connector_settings()
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/client/settings.py", line 435, in create_connector_settings
    type=ConnectorType[connection_spec["trading_type"]],
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'AMM'
2023-05-19 18:55:33,427 - 5669 - hummingbot.core.gateway.gateway_status_monitor - INFO - Connection to Gateway container lost...
2023-05-19 19:00:59,963 - 5669 - hummingbot.core.gateway.gateway_status_monitor - INFO - Gateway Service is ONLINE.
2023-05-19 19:01:49,052 - 6383 - hummingbot.core.gateway.gateway_status_monitor - INFO - Gateway Service is ONLINE.
2023-05-19 19:02:28,435 - 6415 - hummingbot.core.gateway.gateway_status_monitor - INFO - Gateway Service is ONLINE.
2023-05-19 19:03:57,789 - 6456 - hummingbot.core.gateway.gateway_status_monitor - INFO - Gateway Service is ONLINE.
2023-05-19 19:06:57,483 - 8193 - hummingbot.core.gateway.gateway_status_monitor - INFO - Gateway Service is ONLINE.
2023-05-19 19:07:14,489 - 8193 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'AMM'
Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/client/command/gateway_command.py", line 321, in _gateway_connect
    AllConnectorSettings.create_connector_settings()
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/client/settings.py", line 435, in create_connector_settings
    type=ConnectorType[connection_spec["trading_type"]],
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'AMM'
```

This error also affects the client when we tried to relaunch making it unusable at the moment.
![image](https://github.com/hummingbot/gateway/assets/73840223/9c182188-260c-4eb4-88e5-b58e6c6f87a1)
  - **Work around is to delete the  `../conf/gateway_connections.json` file and client will work again**
  - The last working commit was `6d7b639ddd219b4fad60b7cf612c2a81c2bf0076`
  - Crosscheck on mbp(m1) and WSL ubuntu20.04 getting same behavior

**Steps To Reproduce**
1. Setup client and gateway latest development branch
2. Connect any AMM connector wallet then observe behavior
3. Relaunch client to observe behavior of the bug

**Release version**
Development dev-1.16.0

**Attachments**
[logs_hummingbot.log](https://github.com/hummingbot/gateway/files/11516300/logs_hummingbot.log)

**Comment by rapcmia** [comment]
Fixed on latest Client development branch
