### ISSUE TITLE
Uniswap router not returning prices

### ISSUE THREAD

**Issue by toxicehc** [hummingbot/gateway#150]
### Describe the bug

Since yesterday I cannot get the price of a pair on uniswap polygon.

### Steps to reproduce

1. Clean install v17 source
2. Create amm_arb strategy
3. Start strategy - gets stuck on 'starting networking' - reports errors
4. 
![image](https://github.com/hummingbot/hummingbot/assets/4660657/a9709211-5360-4c8b-ae1c-c3711fe9eb43)
Log files indicate:
2023-06-29 15:28:06,510 - 10872 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/price failed. See logs for more details.
2023-06-29 15:28:06,510 - 10872 - GatewayEVMAMM - WARNING - Error on POST https://localhost:15888/amm/price Error: {'message': 'Price query failed: Request failed with status code 522', 'httpErrorCode': 500, 'errorCode': 1013, 'stack': 'Error: Price query failed: Request failed with status code 522\n    at /home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:74:23\n    at Generator.throw (<anonymous>)\n    at rejected (/home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)'}
2023-06-29 15:28:06,813 - 10872 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/price failed. See logs for more details.
2023-06-29 15:28:06,814 - 10872 - GatewayEVMAMM - WARNING - Error on POST https://localhost:15888/amm/price Error: {'message': 'Price query failed: Request failed with status code 522', 'httpErrorCode': 500, 'errorCode': 1013, 'stack': 'Error: Price query failed: Request failed with status code 522\n    at /home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:74:23\n    at Generator.throw (<anonymous>)\n    at rejected (/home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)'}
2023-06-29 15:28:22,161 - 10872 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/price failed. See logs for more details.
2023-06-29 15:28:22,161 - 10872 - GatewayEVMAMM - WARNING - Error on POST https://localhost:15888/amm/price Error: {'message': 'Price query failed: Request failed with status code 522', 'httpErrorCode': 500, 'errorCode': 1013, 'stack': 'Error: Price query failed: Request failed with status code 522\n    at /home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:74:23\n    at Generator.throw (<anonymous>)\n    at rejected (/home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)'}
2023-06-29 15:28:22,161 - 10872 - hummingbot.strategy.amm_arb.amm_arb - INFO - No arbitrage opportunity.

### Release version

V1.17

### Type of installation

Source

### Attach required files

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/11906202/logs_hummingbot.log)
[logs_conf_amm_arb_1.log](https://github.com/hummingbot/hummingbot/files/11906203/logs_conf_amm_arb_1.log)

**Comment by emusol** [comment]
currently adding liquidity positions dont work also with the fix on the development branch, the issue with the liquidity started 2 weeks ago aswell
