### ISSUE TITLE
Docker Compose Method from DEV1.18 to Latest 1.18 gives errors

### ISSUE THREAD

**Issue by toxicehc** [hummingbot/gateway#180]
update config to latest
docker pull
docker compose pull
then docker compose up -d
then docker attach gateway
and then the gateway was looping like this:

Node.js v18.10.0
Gateway API server stopped unexpectedly. Restarting...
/home/gateway/dist/src/services/config-manager-v2.js:92
            throw new Error(`The JSON schema for namespace ${id} (${schemaPath}) does not exist.`);
            ^

Error: The JSON schema for namespace defikingdoms (/home/gateway/dist/src/services/schema/defikingdoms-schema.json) does not exist.
    at new ConfigurationNamespace (/home/gateway/dist/src/services/config-manager-v2.js:92:19)
    at ConfigManagerV2.addNamespace (/home/gateway/dist/src/services/config-manager-v2.js:227:78)
    at ConfigManagerV2.loadConfigRoot (/home/gateway/dist/src/services/config-manager-v2.js:296:18)
    at new ConfigManagerV2 (/home/gateway/dist/src/services/config-manager-v2.js:193:14)
    at ConfigManagerV2.getInstance (/home/gateway/dist/src/services/config-manager-v2.js:186:41)
    at getLogPath (/home/gateway/dist/src/services/logger.js:43:55)
    at Object.<anonymous> (/home/gateway/dist/src/services/logger.js:49:18)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)

Delete contents of folder restart no improvement

**Comment by fengtality** [comment]
If you installed from Docker, I suggest removing the old Docker image with `docker image rm hummingbot/gateway:main` so that it has to fetch the new image

**Comment by toxicehc** [comment]
Hello Mike - that command does not work, however docker image rm hummingbot/gateway:main does.
The error however persists.
Any other advice?

**Comment by toxicehc** [comment]
I also tried by updating the compose.yml file to explicitely use version-1.18.0 - which forced a fresh download and still the same result.

**Comment by rapcmia** [comment]
Hi @toxicehc good day
I sent you a DM on discord to assist you further on this ticket. Id like to understand how this issue occurred. Thank you
