### ISSUE TITLE
Algorand chain/Tinyman DEX: can't add wallet

### ISSUE THREAD

**Issue by rob-ti** [hummingbot/gateway#185]
**Describe the bug**
When trying to connect to Tinyman (Dex on Algorand), the private key/mnemonic is not recognized and an error is thrown.

**Steps To Reproduce**
Connect to tinyman (testnet or mainnet, doesn't matter) and try to add your private key (or mnemonic, tested with both). An error is thrown

` | error |   The privateKey param is not a valid Algorand private key or mnemonic. | Error: The privateKey param is not a valid Algorand private key or mnemoc.
    at throwIfErrorsExist (/home/gateway/dist/src/services/validators.js:38:15)
    at /home/gateway/dist/src/services/validators.js:103:40
    at /home/gateway/dist/src/services/wallet/wallet.routes.js:25:58
    at Generator.next (<anonymous>)
    at /home/gateway/dist/src/services/wallet/wallet.routes.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/gateway/dist/src/services/wallet/wallet.routes.js:4:12)
    at /home/gateway/dist/src/services/wallet/wallet.routes.js:24:86
    at /home/gateway/dist/src/services/error-handler.js:37:28
    at Layer.handle [as handle_request] (/home/gateway/node_modules/express/lib/router/layer.js:95:5)`

I've tested it with the same private key/mnemonic that I use with the official Algorand SDK with no issues.

**Release version**
Tested with the latest docker image and installation from source (main and development branches)

**Comment by rob-ti** [comment]
nvm, my mistake. please delete this.
