### ISSUE TITLE
Dexalot - Failed to create or cancel order due to Network error

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#200]
**Describe the bug**
When connector is trying to cancel an order, there are instances of network error causing the order to be not recognized by the client and stuck on exchange

Client log file:
```
2023-09-15 11:06:17,077 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba929e526bbe6. [clock=2023-09-15 11:06:17+00:00]
2023-09-15 11:06:17,077 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba929e526be12. [clock=2023-09-15 11:06:17+00:00]
2023-09-15 11:06:18,810 - 16 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15884/clob/batchOrders failed. See logs for more details.
2023-09-15 11:06:18,811 - 16 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - ERROR - Failed to cancel order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba929e526be12
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 677, in _execute_order_cancel_and_process_update
    cancelled, misc_order_updates = await self._api_data_source.cancel_order(order=order)
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 109, in cancel_order
    cancel_order_results = await super().batch_order_cancel(orders_to_cancel=[order])
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/data_sources/gateway_clob_api_data_source_base.py", line 277, in batch_order_cancel
    update_result = await self._get_gateway_instance().clob_batch_order_modify(
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 953, in clob_batch_order_modify
    return await self.api_request("post", "clob/batchOrders", request_payload)
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15884/clob/batchOrders Error: {'message': 'Network error. Please check your node URL, API key, and Internet connection.', 'httpErrorCode': 503, 'errorCode': 1001, 'stack': 'Error: processing response error (body="{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1694,\\"error\\":{\\"code\\":-32000,\\"message\\":\\"transaction would cause overdraft\\"}}", error={"code":-32000}, requestBody="{\\"method\\":\\"eth_sendRawTransaction\\",\\"params\\":[\\"0x02f8d68306984c8205d68459682f008505017ff700832dc6c09409383137c1eee3e1a8bc781228e4199f6b4a9bbf80b8640cf80dda000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000064b3be52c001a08f45ee46b5de96971b090d6b3bf0ab63e7db780e3021545e23016b767152f113a035bc87b9b943d153b5659261593428458ef868aff691a03d5379e1e18bf78271\\"],\\"id\\":1694,\\"jsonrpc\\":\\"2.0\\"}", requestMethod="POST", url="https://subnets.avax.network/dexalot/mainnet/rpc", code=SERVER_ERROR, version=web/5.7.1)\n    at Logger.makeError (/home/gateway/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/gateway/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at /home/gateway/node_modules/@ethersproject/web/lib/index.js:313:32\n    at step (/home/gateway/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/home/gateway/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/home/gateway/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
```

Gateway logs:
```
::ffff:192.168.112.1 - - [15/Sep/2023:11:05:50 +0000] "POST /chain/balances HTTP/1.1" 200 461 "-" "Python/3.10 aiohttp/3.8.5"
::ffff:192.168.112.1 - - [15/Sep/2023:11:05:55 +0000] "POST /chain/balances HTTP/1.1" 200 461 "-" "Python/3.10 aiohttp/3.8.5"
::ffff:192.168.112.1 - - [15/Sep/2023:11:06:00 +0000] "POST /chain/balances HTTP/1.1" 200 461 "-" "Python/3.10 aiohttp/3.8.5"
::ffff:192.168.112.1 - - [15/Sep/2023:11:06:05 +0000] "POST /chain/balances HTTP/1.1" 200 461 "-" "Python/3.10 aiohttp/3.8.5"
::ffff:192.168.112.1 - - [15/Sep/2023:11:06:10 +0000] "POST /chain/balances HTTP/1.1" 200 461 "-" "Python/3.10 aiohttp/3.8.5"
::ffff:192.168.112.1 - - [15/Sep/2023:11:06:15 +0000] "POST /chain/balances HTTP/1.1" 200 461 "-" "Python/3.10 aiohttp/3.8.5"
::ffff:192.168.112.1 - - [15/Sep/2023:11:06:18 +0000] "POST /clob/batchOrders HTTP/1.1" 200 160 "-" "Python/3.10 aiohttp/3.8.5"
2023-09-16 12:26:18 | error |   processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":1694,\"error\":{\"code\":-32000,\"message\":\"transaction would cause overdraft\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8d68306984c8205d68459682f008505017ff700832dc6c09409383137c1eee3e1a8bc781228e4199f6b4a9bbf80b8640cf80dda000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000064b3be52c001a08f45ee46b5de96971b090d6b3bf0ab63e7db780e3021545e23016b767152f113a035bc87b9b943d153b5659261593428458ef868aff691a03d5379e1e18bf78271\"],\"id\":1694,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://subnets.avax.network/dexalot/mainnet/rpc", code=SERVER_ERROR, version=web/5.7.1)
2023-09-16 12:26:18 | error |   processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":1694,\"error\":{\"code\":-32000,\"message\":\"transaction would cause overdraft\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8d68306984c8205d68459682f008505017ff700832dc6c09409383137c1eee3e1a8bc781228e4199f6b4a9bbf80b8640cf80dda000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000064b3be52c001a08f45ee46b5de96971b090d6b3bf0ab63e7db780e3021545e23016b767152f113a035bc87b9b943d153b5659261593428458ef868aff691a03d5379e1e18bf78271\"],\"id\":1694,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://subnets.avax.network/dexalot/mainnet/rpc", code=SERVER_ERROR, version=web/5.7.1)
```

**Steps To Reproduce**
1. Setup dexalot on PMM with gateway connection
2. Observe behavior on cancellation event

**Release version**
dev-1.20.0 and 1.19.0

**Attachments**
[logs_pmm_dexalot-01_trimmed.log](https://github.com/hummingbot/gateway/files/12619575/logs_pmm_dexalot-01_trimmed.log)

**Comment by aravivek07** [comment]
I just face the exact same problem. Is there any workaround for this issue?

**Comment by petioptrv** [comment]
Investigating this issue now. Has this been only observed with order cancelations? Or it has been spotted with order creations as well?

**Comment by petioptrv** [comment]
Thank you for the confirmation @rapcmia. It looks like this is a message issued by the chain to indicate lack of gas to execute the transaction. On the second log, I can see that the cancelation problem happens with `0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba929e526be12`, but the subsequent attempt is successful. The first log is truncated. Was it the case that the bot tried multiple times to cancel and finally abandoned the order as "lost"?

**Comment by petioptrv** [comment]
Also, I'd like to confirm whether it's possible the bot was actually out of gas for those transactions?

**Comment by rapcmia** [comment]
> Thank you for the confirmation @rapcmia. It looks like this is a message issued by the chain to indicate lack of gas to execute the transaction. On the second log, I can see that the cancelation problem happens with `0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba929e526be12`, but the subsequent attempt is successful. The first log is truncated. Was it the case that the bot tried multiple times to cancel and finally abandoned the order as "lost"?

Ahh yes the initial logs was related to the multiple attempt to cancel the order. We had enough balance to execute transaction but i assume it was allocated on the order that was created but not recognized by the connector. 

> Also, I'd like to confirm whether it's possible the bot was actually out of gas for those transactions?

I would assume that would be the case, We are running a long term bot now and we can use the log files to review this issue again. Will add update tonight 🙇

**Comment by petioptrv** [comment]
@rapcmia, what is puzzling me is that it shouldn't be the case that the bot abandons the order in this case, but you mention that this caused an orphaned order. When this happens again in the long-running logs, please send a version of the logs from the moment that the order creation request is issued by the client, to the moment where the client drops the order (considers it as lost). If the log is large, maybe you can share it using a cloud service, but it's important that we get the full history for that order

**Comment by rapcmia** [comment]
Hi @petioptrv thanks for your time.
Upon reviewing again this issue, unable to reproduce and confirmed related to insufficient `dexalot gas tank` closing ticket.
