### ISSUE TITLE
Dexalot - Stuck on cancelling order

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#201]
**Describe the bug**
Reviewed logs of long term bot running for 3 days and observed that the connector has been stuck on `Canceling the limit order...` following up with different error messages:

Due to server disconnected:
```
+00:00]
2023-09-15 13:39:26,012 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 13:39:26+00:00]
2023-09-15 13:40:27,011 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 13:40:27+00:00]
2023-09-15 13:41:28,001 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 13:41:28+00:00]
2023-09-15 13:42:29,030 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 13:42:29+00:00]
2023-09-15 13:43:30,009 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 13:43:30+00:00]
2023-09-15 13:43:30,713 - 16 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15884/clob/batchOrders failed. See logs for more details.
2023-09-15 13:43:30,714 - 16 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - ERROR - Failed to cancel order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 677, in _execute_order_cancel_and_process_update
    cancelled, misc_order_updates = await self._api_data_source.cancel_order(order=order)
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 109, in cancel_order
    cancel_order_results = await super().batch_order_cancel(orders_to_cancel=[order])
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/data_sources/gateway_clob_api_data_source_base.py", line 277, in batch_order_cancel
    update_result = await self._get_gateway_instance().clob_batch_order_modify(
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 953, in clob_batch_order_modify
    return await self.api_request("post", "clob/batchOrders", request_payload)
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 187, in api_request
    response = await client.post(url, json=params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

```

---

Due to missing revert data in call exception; Transaction reverted without a reason string
```
2023-09-15 17:25:08,002 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 17:25:08+00:00]
2023-09-15 17:26:09,001 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 17:26:09+00:00]
2023-09-15 17:27:10,002 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 17:27:10+00:00]
2023-09-15 17:28:11,002 - 16 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALOT-USDC) Canceling the limit order 0x0000000000000000001dfd846dc347698bb165cc223fc2180d1ba92bbc8e8023. [clock=2023-09-15 17:28:11+00:00]
2023-09-15 17:28:45,136 - 16 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15884/chain/balances failed. See logs for more details.
2023-09-15 17:28:45,137 - 16 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to update balances. Error: Error on POST https://localhost:15884/chain/balances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0xa5C079C1986E2335d83fA2d7282e162958e515D5","data":"0xc79d5ec500000000000000000000000008940dc9b5a19fab9319b77c61dda7b8067e68437441564158000000000000000000000000000000000000000000000000000000","accessList":null}, error={"reason":"bad response","code":"SERVER_ERROR","status":405,"headers":{"date":"Fri, 15 Sep 2023 17:28:45 GMT","content-length":"0","connection":"close","access-control-allow-origin":"*","referrer-policy":"strict-origin-when-cross-origin","report-to":"{\\"endpoints\\":[{\\"url\\":\\"https:\\\\/\\\\/a.nel.cloudflare.com\\\\/report\\\\/v3?s=lXtPz%2FwnZ0CBAwCl7J2QG84cdlOTJePqSGsnexeaLTo%2F5NIsWeO2ulwLN3LAYdUDz3WcEvnPTdEytLxqj4RKL4jB1lLsOyjdXzcuG7ibywaPrJjw1F%2FJ53W7i%2FkSAAtpn3kqjQNF1Q%3D%3D\\"}],\\"group\\":\\"cf-nel\\",\\"max_age\\":604800}","nel":"{\\"success_fraction\\":0,\\"report_to\\":\\"cf-nel\\",\\"max_age\\":604800}","vary":"Accept-Encoding","cf-cache-status":"DYNAMIC","set-cookie":"__cf_bm=nqRbPGf7alvS7KG2294IqoIC0Ft1Es9InFwqSl0Fkbw-1694798925-0-AcQoWdpKiAH9hl/VaWIYyZXn24WN6o6EVcY9selG/uzT8TM6yX2faiI0Ec5nr15gIJBVQRLJ+0eCKDEOnHXzTsk=; path=/; expires=Fri, 15-Sep-23 17:58:45 GMT; domain=.avax.network; HttpOnly; Secure","strict-transport-security":"max-age=0","server":"cloudflare","cf-ray":"80729681c8d2af7c-NRT"},"body":null,"requestBody":"{\\"method\\":\\"eth_call\\",\\"params\\":[{\\"to\\":\\"0xa5c079c1986e2335d83fa2d7282e162958e515d5\\",\\"data\\":\\"0xc79d5ec500000000000000000000000008940dc9b5a19fab9319b77c61dda7b8067e68437441564158000000000000000000000000000000000000000000000000000000\\"},\\"latest\\"],\\"id\\":44706,\\"jsonrpc\\":\\"2.0\\"}","requestMethod":"POST","url":"https://subnets.avax.network/dexalot/mainnet/rpc"}, code=CALL_EXCEPTION, version=providers/5.7.2)\n    at Logger.makeError (/home/gateway/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/gateway/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at checkError (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:108:16)\n    at StaticJsonRpcProvider.<anonymous> (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)\n    at step (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 938, in _update_all_balances
    await self._update_balances()
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 571, in _update_balances
    balances = await self._api_data_source.get_account_balances()
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 145, in get_account_balances
    result = await self._get_gateway_instance().get_balances(
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 289, in get_balances
    return await self.api_request(
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15884/chain/balances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0xa5C079C1986E2335d83fA2d7282e162958e515D5","data":"0xc79d5ec500000000000000000000000008940dc9b5a19fab9319b77c61dda7b8067e68437441564158000000000000000000000000000000000000000000000000000000","accessList":null}, error={"reason":"bad response","code":"SERVER_ERROR","status":405,"headers":{"date":"Fri, 15 Sep 2023 17:28:45 GMT","content-length":"0","connection":"close","access-control-allow-origin":"*","referrer-policy":"strict-origin-when-cross-origin","report-to":"{\\"endpoints\\":[{\\"url\\":\\"https:\\\\/\\\\/a.nel.cloudflare.com\\\\/report\\\\/v3?s=lXtPz%2FwnZ0CBAwCl7J2QG84cdlOTJePqSGsnexeaLTo%2F5NIsWeO2ulwLN3LAYdUDz3WcEvnPTdEytLxqj4RKL4jB1lLsOyjdXzcuG7ibywaPrJjw1F%2FJ53W7i%2FkSAAtpn3kqjQNF1Q%3D%3D\\"}],\\"group\\":\\"cf-nel\\",\\"max_age\\":604800}","nel":"{\\"success_fraction\\":0,\\"report_to\\":\\"cf-nel\\",\\"max_age\\":604800}","vary":"Accept-Encoding","cf-cache-status":"DYNAMIC","set-cookie":"__cf_bm=nqRbPGf7alvS7KG2294IqoIC0Ft1Es9InFwqSl0Fkbw-1694798925-0-AcQoWdpKiAH9hl/VaWIYyZXn24WN6o6EVcY9selG/uzT8TM6yX2faiI0Ec5nr15gIJBVQRLJ+0eCKDEOnHXzTsk=; path=/; expires=Fri, 15-Sep-23 17:58:45 GMT; domain=.avax.network; HttpOnly; Secure","strict-transport-security":"max-age=0","server":"cloudflare","cf-ray":"80729681c8d2af7c-NRT"},"body":null,"requestBody":"{\\"method\\":\\"eth_call\\",\\"params\\":[{\\"to\\":\\"0xa5c079c1986e2335d83fa2d7282e162958e515d5\\",\\"data\\":\\"0xc79d5ec500000000000000000000000008940dc9b5a19fab9319b77c61dda7b8067e68437441564158000000000000000000000000000000000000000000000000000000\\"},\\"latest\\"],\\"id\\":44706,\\"jsonrpc\\":\\"2.0\\"}","requestMethod":"POST","url":"https://subnets.avax.network/dexalot/mainnet/rpc"}, code=CALL_EXCEPTION, version=providers/5.7.2)\n    at Logger.makeError (/home/gateway/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/gateway/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at checkError (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:108:16)\n    at StaticJsonRpcProvider.<anonymous> (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)\n    at step (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/home/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
```

**Steps To Reproduce**
1. Setup PMM on Dexalot w/ Gateway 
2. Run for couple of hours and review log files 

**Release version**
dev-1.20.0 and v1.19.0

**Attachments**
[logs_pmm-dexalot-01.log.2023-09-15.log](https://github.com/hummingbot/gateway/files/12646892/logs_pmm-dexalot-01.log.2023-09-15.log)
[logs_pmm-dexalot-01.log.2023-09-16.log](https://github.com/hummingbot/gateway/files/12646893/logs_pmm-dexalot-01.log.2023-09-16.log)
[pmm-dexalot-01.yml.log](https://github.com/hummingbot/gateway/files/12646916/pmm-dexalot-01.yml.log)
[logs_gateway_app.log.2023-09-15.log](https://github.com/hummingbot/gateway/files/12646956/logs_gateway_app.log.2023-09-15.log)
[logs_gateway_app.log.2023-09-16.log](https://github.com/hummingbot/gateway/files/12646957/logs_gateway_app.log.2023-09-16.log)

**Comment by petioptrv** [comment]
Hey @rapcmia, I think we need additional logging to diagnose these issues. I've created two branches that add additional debugging statements to both the [client](https://github.com/CoinAlpha/hummingbot/tree/fix/debugging-dexalot) and [gateway](https://github.com/CoinAlpha/gateway/tree/fix/debugging-dexalot) Dexalot connectors. Can you please run a long-standing test from those two branches and post the logs here once the issue has been reproduced? **Please remember to enable debug logging for both Gateway and the Client so that the logs work!**

**Comment by rapcmia** [comment]
> I've created two branches that add additional debugging statements to both the [client](https://github.com/CoinAlpha/hummingbot/tree/fix/debugging-dexalot) and [gateway](https://github.com/CoinAlpha/gateway/tree/fix/debugging-dexalot) Dexalot connectors.

Hi @petioptrv good day, 
the branches wont let me connect to `dexalot` getting error `Unhandled error in background task: 'str' object has no attribute 'get'`
![image](https://github.com/hummingbot/gateway/assets/73840223/4d3c4491-4b3b-4b9a-a032-5a950117643d)
```
2023-10-05 06:43:00,192 - 854296 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/ralph/github/hummingbot/issue201/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ralph/github/hummingbot/issue201/hummingbot/client/command/gateway_command.py", line 240, in _gateway_connect
    await self._test_node_url_from_gateway_config(chain, network, attempt_connection=False)
  File "/home/ralph/github/hummingbot/issue201/hummingbot/client/command/gateway_api_manager.py", line 83, in _test_node_url_from_gateway_config
    config_dict: Dict[str, Any] = await GatewayHttpClient.get_instance().get_configuration()
  File "/home/ralph/github/hummingbot/issue201/hummingbot/core/gateway/gateway_http_client.py", line 272, in get_configuration
    return await self.api_request("get", "chain/config", fail_silently=fail_silently)
  File "/home/ralph/github/hummingbot/issue201/hummingbot/core/gateway/gateway_http_client.py", line 222, in api_request
    raise e
  File "/home/ralph/github/hummingbot/issue201/hummingbot/core/gateway/gateway_http_client.py", line 205, in api_request
    self.log_error_codes(parsed_response)
  File "/home/ralph/github/hummingbot/issue201/hummingbot/core/gateway/gateway_http_client.py", line 112, in log_error_codes
    error_code: Optional[int] = resp.get("errorCode")
AttributeError: 'str' object has no attribute 'get'
```

Steps:
1. Clone client and gateway
2. Setup gateway connection then connect dexalot

[logs_hummingbot.log](https://github.com/hummingbot/gateway/files/12813154/logs_hummingbot.log)

**Comment by petioptrv** [comment]
@rapcmia, I have pushed several fixes to both logging branches. Please try to reproduce the issue again using the debugging logs (please remember to enable debugging level for both client and gateway logs)

**Comment by rapcmia** [comment]
Hi @petioptrv after running dexalot today, we had not able to reproduce this issue. We are assuming this has something to do with `dexalot gas tank` which seems to be insufficient when we tested dexalot. Now after running for 4-5hours today im not seeing any related to suck on cancellation.

![image](https://github.com/hummingbot/gateway/assets/73840223/c90a1a29-4c45-4320-8ded-cf0e8bf07ea3)

We'll close the ticket now and shall reopen if issue happens again

**Comment by petioptrv** [comment]
> Hi @petioptrv after running dexalot today, we had not able to reproduce this issue. We are assuming this has something to do with `dexalot gas tank` which seems to be insufficient when we tested dexalot. Now after running for 4-5hours today im not seeing any related to suck on cancellation.
> 
> ![image](https://user-images.githubusercontent.com/73840223/274274287-c90a1a29-4c45-4320-8ded-cf0e8bf07ea3.png)
> 
> We'll close the ticket now and shall reopen if issue happens again

@rapcmia, did you test using my "debugging" branch? Because that branch has code changes on it that will affect the operation of the bot. Notably, [this commit](https://github.com/CoinAlpha/hummingbot/commit/2508cb39b1067d7231052ed1d0873bd9c2cd80d0). If that's the case, then we'd still need a PR to merge those changes.

**Comment by rapcmia** [comment]
Hi @petioptrv yes, debug is enabled on the client and gateway. Cloned the linked branch and not able to reproduce the scenario of stuck on cancelling order

Attached:
[hummingbot_logs.yml.log](https://github.com/hummingbot/gateway/files/12918083/hummingbot_logs.yml.log) `client log config`
For gateway, changed `logger.info` to `logger.debug` from `../src/app.ts`
[logs_pmm-dexalot-01.log](https://github.com/hummingbot/gateway/files/12918166/logs_pmm-dexalot-01.log)
[logs_gateway_app.log.2023-10-11.log](https://github.com/hummingbot/gateway/files/12918170/logs_gateway_app.log.2023-10-11.log)
[pmm-dexalot-01.yml.log](https://github.com/hummingbot/gateway/files/12918179/pmm-dexalot-01.yml.log)
