### ISSUE TITLE
Dexalot - Submitted order failed on client but successful on exchange

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#209]
**Describe the bug**
While running tests on another github ticket for `dexalot`, we observed that when the client tries to create orders there are instances of order has failed yet on exchange it was successfully posted

Recording: https://drive.google.com/file/d/1V5b-QnkJHYBobF9eLmav6cD1ZaiwHKr6/view?usp=sharing
- On 2:30s:
    - The client displayed both orders for few secs then BUY was removed
    - When reaching the refresh time, only the SELL order was cancelled and BUY order was not recognized and stuck on exchange
    - Found the [txhash 0x0d78edf944fb8aee82aca5aa6f94c89e35974becd82d4041c670fed946cff619](https://subnets.avax.network/dexalot/tx/0x6cf62f7e34f74a7d777d2444002a69d5df74da7967ad477949b2d69c3378f502) gw logs

Snippet from the attached log file where the `0x00000000000000000003c1ebb3b741f516111c24fe4ce8e8be8e1aec89771569` is the order if of failed order on client but successful on exchange :
```
# Creating orders (3)
2023-09-29 03:55:12,076 - 15 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AVAX-USDC) Creating 1 bid orders at (Size, Price): ['0.75 AVAX, 9.234 USDC']
2023-09-29 03:55:12,077 - 15 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AVAX-USDC) Creating 1 ask orders at (Size, Price): ['0.75 AVAX, 9.42 USDC']
2023-09-29 03:55:15,686 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1695959715.0, "order_id": "0x00000000000000000003c1ebb3b741f516111c24fe4ce8e8be8e1aec89771569", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "dexalot_avalanche_dexalot"}
2023-09-29 03:55:15,686 - 15 - hummingbot.connector.client_order_tracker - INFO - Order 0x00000000000000000003c1ebb3b741f516111c24fe4ce8e8be8e1aec89771569 has failed. Order Update: OrderUpdate(trading_pair='AVAX-USDC', update_timestamp=1695959715.6809342, new_state=<OrderState.FAILED: 6>, client_order_id='0x00000000000000000003c1ebb3b741f516111c24fe4ce8e8be8e1aec89771569', exchange_order_id=None, misc_updates=None)
2023-09-29 03:55:45,725 - 15 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch trade updates for order 0x00000000000000000003c1ebb3b741f516111c24fe4ce8e8be8e1aec89771569. Error: 
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/gateway/gateway_in_flight_order.py", line 102, in get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/opt/conda/envs/hummingbot/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 954, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 599, in _all_trade_updates_for_order
    trade_updates = await self._api_data_source.get_all_order_fills(in_flight_order=order)
  File "/home/hummingbot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 195, in get_all_order_fills
    "orderid": await in_flight_order.get_exchange_order_id(),
  File "/home/hummingbot/hummingbot/connector/gateway/gateway_in_flight_order.py", line 101, in get_exchange_order_id
    async with timeout(GET_GATEWAY_EX_ORDER_ID_TIMEOUT):
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

![image](https://github.com/hummingbot/gateway/assets/73840223/ac065271-70b5-49fb-a8c1-f02c3033e7c4)
- Shows on dexalot explorer that it was successfully submitted and only the buy order was cancelled on the refresh time

Tried to run `stop` command to check if it can still fetch the stuck order but no avail. There are 2 instances of this issue on the attached log file with added comments

**Steps To Reproduce**
1. Account must have enough gas to create and cancel order, make sure to check the `balances > dexalot gas tank`
2. Setup PMM with Dexalot
3. Observe the connector when creating orders

**Release version**
dev-1.20.0

**Attachments**
[logs_pmm-dexalot-01.log](https://github.com/hummingbot/gateway/files/12756460/logs_pmm-dexalot-01.log)
[logs_gateway_app.log.2023-09-29.log](https://github.com/hummingbot/gateway/files/12756465/logs_gateway_app.log.2023-09-29.log)
[pmm-dexalot-01.yml.log](https://github.com/hummingbot/gateway/files/12756481/pmm-dexalot-01.yml.log) `remove .log`

**Comment by mrhzysbl** [comment]
Recording: https://drive.google.com/file/d/1vJPsdnYBO44hItVCNtCwtZxpCduarG5w/view?usp=sharing

In this scenario, the client was able to create two orders: 

<img width="1297" alt="image" src="https://github.com/hummingbot/gateway/assets/120451804/39905aac-9fc8-455f-bda1-f376f6487544">

``` ruby
2023-10-04 17:04:46,003 - 15622 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AVAX-USDC) Creating 1 bid orders at (Size, Price): ['2 AVAX, 9.552 USDC']
2023-10-04 17:04:46,004 - 15622 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (AVAX-USDC) Creating 1 ask orders at (Size, Price): ['2 AVAX, 9.942 USDC']
```
``` ruby
2023-10-04 17:04:47,030 - 15622 - hummingbot.connector.gateway.clob_spot.data_sources.dexalot.dexalot_api_data_source.DexalotAPIDataSource - DEBUG - Order creation transaction hash for 0x0000000000000000001f9679ab04b2eab7c9f0bcf9421b7e3fdf8c2f219396ff: 0x0c0822f09f9d414eaf95cdd38454ab3d845435d3290b30ba3642cf370cabccc6
2023-10-04 17:04:48,001 - 15622 - hummingbot.connector.gateway.clob_spot.data_sources.dexalot.dexalot_api_data_source.DexalotAPIDataSource - DEBUG - Order creation transaction hash for 0x0000000000000000001f9679ab04b2eab7c9f0bcf9421b7e3fdf8c2f219397b0: 0x3a790c054d019e27b5f4a96e585789c04f7629dcf9dcd5c1ae7912dfae93967f
```


Tx hash for BUY order: [0x0c0822f09f9d414eaf95cdd38454ab3d845435d3290b30ba3642cf370cabccc6](https://subnets.avax.network/dexalot/tx/0x0c0822f09f9d414eaf95cdd38454ab3d845435d3290b30ba3642cf370cabccc6)
Tx hash for SELL order: 0x3a790c054d019e27b5f4a96e585789c04f7629dcf9dcd5c1ae7912dfae93967f - not found in Dexalot Explorer and got this error:
``` ruby
2023-10-04 17:04:52,801 - 15622 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1696410292.0, "order_id": "0x0000000000000000001f9679ab04b2eab7c9f0bcf9421b7e3fdf8c2f219397b0", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "dexalot_avalanche_dexalot"}
```

After a few seconds (00:27 mark), only the BUY order was left on client and had an order. This BUY order showed on exchange:

``` ruby
2023-10-04 17:04:50,297 - 15622 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order 0x0000000000000000001f9679ab04b2eab7c9f0bcf9421b7e3fdf8c2f219396ff for 2.000 AVAX-USDC.
```

Then we are also getting this warning: 
``` ruby
2023-10-04 17:04:52,133 - 15622 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Error fetching status update for the active order 0x0000000000000000001f9679ab04b2eab7c9f0bcf9421b7e3fdf8c2f219396ff: No update found for order 0x0000000000000000000000000000000000000000000000000000000064e493c5..
```

Eventually, the order failed to cancel in the client app but not on the exchange based on the [txhash](https://subnets.avax.network/dexalot/tx/0x0c0822f09f9d414eaf95cdd38454ab3d845435d3290b30ba3642cf370cabccc6): 

``` ruby
2023-10-04 17:05:08,837 - 15622 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - ERROR - Failed to cancel order 0x0000000000000000001f9679ab04b2eab7c9f0bcf9421b7e3fdf8c2f219396ff
Traceback (most recent call last):
  File "/Users/admin/dexalot/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/Users/admin/dexalot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 677, in _execute_order_cancel_and_process_update
    cancelled, misc_order_updates = await self._api_data_source.cancel_order(order=order)
  File "/Users/admin/dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 119, in cancel_order
    cancel_order_results = await super().batch_order_cancel(orders_to_cancel=[order])
  File "/Users/admin/dexalot/hummingbot/connector/gateway/clob_spot/data_sources/gateway_clob_api_data_source_base.py", line 277, in batch_order_cancel
    update_result = await self._get_gateway_instance().clob_batch_order_modify(
  File "/Users/admin/dexalot/hummingbot/core/gateway/gateway_http_client.py", line 957, in clob_batch_order_modify
    return await self.api_request("post", "clob/batchOrders", request_payload)
  File "/Users/admin/dexalot/hummingbot/core/gateway/gateway_http_client.py", line 222, in api_request
    raise e
  File "/Users/admin/dexalot/hummingbot/core/gateway/gateway_http_client.py", line 210, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/clob/batchOrders Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1655,\\"error\\":{\\"code\\":-32000,\\"message\\":\\"insufficient funds for gas * price + value: address 0x6Fae3C0a054AE3B3BA3A11B1761848b8D2317f88 have (52096106632001980) want (64500000000000000)\\"}}","error":{"code":-32000},"requestBody":"{\\"method\\":\\"eth_sendRawTransaction\\",\\"params\\":[\\"0x02f8d68306984c82033a8459682f008505017ff700832dc6c09409383137c1eee3e1a8bc781228e4199f6b4a9bbf80b8640cf80dda000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000064e493c5c080a08d74b49c6523856d7b68ab4d6474e975a045a34ffe0e51c824ac6394b2f9ca18a04542842fa569e46719fe867d38603cff1a3f214897b1be3a6d3b6003b41b9392\\"],\\"id\\":1655,\\"jsonrpc\\":\\"2.0\\"}","requestMethod":"POST","url":"https://subnets.avax.network/dexalot/mainnet/rpc"}, method="sendTransaction", transaction="0x02f8d68306984c82033a8459682f008505017ff700832dc6c09409383137c1eee3e1a8bc781228e4199f6b4a9bbf80b8640cf80dda000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000064e493c5c080a08d74b49c6523856d7b68ab4d6474e975a045a34ffe0e51c824ac6394b2f9ca18a04542842fa569e46719fe867d38603cff1a3f214897b1be3a6d3b6003b41b9392", code=INSUFFICIENT_FUNDS, version=providers/5.7.2)\n    at Logger.makeError (/Users/admin/gateway/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/Users/admin/gateway/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at checkError (/Users/admin/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:144:16)\n    at StaticJsonRpcProvider.<anonymous> (/Users/admin/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)\n    at step (/Users/admin/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/Users/admin/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/Users/admin/gateway/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)'}
2023-10-04 17:05:17,111 - 15622 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - NETWORK - Unexpected error cancelling orders.
Traceback (most recent call last):
  File "/Users/admin/dexalot/hummingbot/connector/exchange_py_base.py", line 375, in cancel_all
    cancellation_results = await safe_gather(*tasks, return_exceptions=True)
  File "/Users/admin/dexalot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/dexalot/hummingbot/connector/exchange_py_base.py", line 374, in cancel_all
    async with timeout(timeout_seconds):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```
[Dexalot.zip](https://github.com/hummingbot/gateway/files/12801850/Dexalot.zip)
