### ISSUE TITLE
Upgrading from GATEWAY V1.21 to V1.22 docker image gives an error when starting

### ISSUE THREAD

**Issue by toxicehc** [hummingbot/gateway#243]
When updating the docker image from Version 1.21 to Version 1.22 I am receiving the following error in the gateway docker instance:

Gateway API server stopped unexpectedly. Restarting...
/home/gateway/dist/src/services/config-manager-v2.js:123
                        throw new Error(`${this.id} config file seems to be outdated/broken due to additional property "${err.params.additionalProperty}". Kindly fix manually.`);
                        ^

Error: plenty config file seems to be outdated/broken due to additional property "ctezAdmin". Kindly fix manually.
    at ConfigurationNamespace.loadConfig (/home/gateway/dist/src/services/config-manager-v2.js:123:31)
    at new ConfigurationNamespace (/home/gateway/dist/src/services/config-manager-v2.js:98:14)
    at ConfigManagerV2.addNamespace (/home/gateway/dist/src/services/config-manager-v2.js:227:78)
    at ConfigManagerV2.loadConfigRoot (/home/gateway/dist/src/services/config-manager-v2.js:296:18)
    at new ConfigManagerV2 (/home/gateway/dist/src/services/config-manager-v2.js:193:14)
    at ConfigManagerV2.getInstance (/home/gateway/dist/src/services/config-manager-v2.js:186:41)
    at getLogPath (/home/gateway/dist/src/services/logger.js:43:55)
    at Object.<anonymous> (/home/gateway/dist/src/services/logger.js:49:18)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)

How to fix this?

**Comment by toxicehc** [comment]
As per rapcmia:
The error was due to update on tezos/plenty. I assume you are using docker so you would need to backup your important files and delete your old gateway folder then run again docker compose again so it will copy the new version.

Confirmed it works now.
